name: DevInfra

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened, reopened]

# Declare default permissions as read only.
permissions:
  contents: read

jobs:
  issue_labels:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - uses: ./github-actions/issue-labeling
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
          google-generative-ai-key: ${{ secrets.GOOGLE_GENERATIVE_AI_KEY }}
