name: Lock issues that are closed and inactive

on:
  schedule:
    # for testing, will run on the 30th minute of every hour
    - cron: '13 * * * *'

jobs:
  lock_closed:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/lock-closed@master
        with:
          lock-bot-key: ${{ secrets.LOCK_BOT_PRIVATE_KEY }}
          locks-per-execution: 1
